export const ADMIN_PRODUCT_COPY = {
    common: {
        loading: '載入中...',
        save: '儲存',
        saving: '儲存中...',
        delete: '刪除',
        backToEdit: '返回產品編輯',
        unsavedChanges: '有尚未儲存的變更',
        confirmLeave: '目前有尚未儲存的內容，離開後變更將不會保留，確定要返回嗎？',
        fetchError: '載入產品資料失敗',
    },
    list: {
        title: '產品管理',
        description: '管理產品資料、分類、前台顯示與排序，並支援匯入匯出與批次操作。',
        exportExcel: '匯出 Excel',
        importExcel: '匯入 Excel',
        manageCategories: '管理分類',
        addProduct: '新增產品',
        allCategories: '全部分類',
        searchPlaceholder: '搜尋產品名稱、品牌、型號或產品說明...',
        selectedCount: (count: number) => `已選取 ${count} 筆產品`,
        batchShow: '批次顯示於前台',
        batchHide: '批次從前台隱藏',
        clearSelection: '取消選取',
        deleteSuccess: '產品已刪除',
        deleteError: '刪除產品失敗',
        batchError: '批次更新前台顯示失敗',
        reorderSuccess: '產品排序已更新',
        reorderError: '更新產品排序失敗',
        fetchError: '載入產品列表失敗',
    },
    newPage: {
        title: '新增產品',
        description: '建立新的產品資料，完成後即可繼續補上前台內容、圖片與 SEO 設定。',
    },
    editPage: {
        title: '編輯產品',
        description: '在這裡調整產品資料、前台內容、SEO 設定與圖片排序。',
        notFound: '找不到這筆產品',
    },
    contentPage: {
        title: '產品內容編輯',
        bodySection: '產品介紹',
        specsSection: '詳細規格',
        videoSection: '產品影片',
        docsSection: '相關文件',
        faqSection: '常見問題 FAQ',
        seoReviewSection: 'SEO 評分與評論（Google Schema）',
        seoReviewHint: '這裡會輸出到前台的 Google 評分與評論結構化資料，請填寫真實可對應的資訊。',
        averageRating: '平均評分（1.0 - 5.0）',
        ratingCount: '評分數量',
        reviewContent: '評論內容',
        addReview: '新增評論',
        noReviews: '目前尚未新增評論',
        noReviewsHint: '如果要輸出 Google Review Schema，可以在這裡補上代表性評論。',
        reviewIndex: (index: number) => `評論 #${index}`,
        reviewAuthorPlaceholder: '評論者名稱，例如：王先生',
        reviewBodyPlaceholder: '輸入評論內容，建議填寫真實、可驗證的使用心得。',
        productIntroPlaceholder: '輸入產品介紹、功能特色、導入優勢與應用情境...',
        reviewCountWarning: (count: number) => `目前評論筆數有 ${count} 筆，建議評分數量不要小於實際評論筆數。`,
        saveSuccess: '產品內容已儲存',
        saveError: '儲存產品內容失敗',
        saveChanges: '儲存變更',
    },
    form: {
        genericSaveError: '儲存失敗',
        confirmTabSwitch: '尚未儲存的內容將會遺失，確定要切換分頁嗎？',
        slugGenerated: (slug: string) => `已產生 slug: ${slug}`,
        slugGenerateError: '無法產生 slug，請先確認品牌、型號或產品名稱。',
        seoPreviewFallbackTitle: '產品標題',
        seoPreviewFallbackDescription: '產品描述摘要...',
        tabs: {
            quote: '報價資料',
            frontend: '前台內容',
            seo: 'SEO',
        },
        quote: {
            saveSuccessNew: '產品已建立',
            saveSuccess: '報價資料已儲存',
            saveButton: '儲存報價資料',
            basicSectionTitle: '基本資料',
            productName: '產品名稱 *',
            productCategory: '產品分類 *',
            productCategoryPlaceholder: '請選擇產品分類...',
            brand: '品牌',
            model: '型號',
            description: '產品說明',
            pricingSectionTitle: '價格與成本設定',
            costPrice: '成本價 *',
            sellingPrice: '售價 *',
            marketPrice: '市場參考價',
            repairPrice: '維修價格',
            unit: '單位',
            inventoryTitle: '啟用庫存追蹤',
            inventoryHint: '開啟後可記錄目前庫存與低庫存提醒門檻。',
            currentStock: '目前庫存',
            lowStockThreshold: '低庫存門檻',
            typeSectionTitle: '產品類型與組合',
            single: '單品',
            bundle: '組合包',
            bundleProduct: '組合商品',
            bundleProductPlaceholder: '選擇商品...',
            quantity: '數量',
            addBundleItem: '新增組合商品',
            bundleEmptyHint: '單品模式不需要設定組合內容；如果要把多個產品一起販售，請切換到組合包。',
            quoteDisplayTitle: '報價顯示設定',
            quoteName: '報價顯示名稱',
            quoteNamePlaceholder: '例如：門禁控制器',
            quoteDescription: '報價顯示說明',
            hiddenItemTitle: '報價單隱藏項目',
            hiddenItemHint: '開啟後此產品只會在後台或特定流程中使用。',
            quickAccessTitle: '快速存取',
            quickAccessHint: '讓這個產品更容易在後台列表或新增流程中被找到。',
            aiTitle: 'AI 產品標記',
            aiHint: '標示這個產品可用於 AI 或智慧化相關分類。',
            hotTitle: '熱門產品標記',
            hotHint: '首頁精選 + 前台快速入口',
            newTitle: '新品標記',
            newHint: '標示這個產品為新品。',
            notesTitle: '備註',
            notesPlaceholder: '輸入內部備註、採購說明或其他補充資訊...',
        },
        frontend: {
            saveBlocked: '請先在 Tab 1 建立產品後，再儲存前台內容。',
            saveSuccess: '前台內容已儲存',
            saveButton: '儲存前台內容',
            websiteVisibilityTitle: '前台網站顯示',
            websiteVisibilityHint: '控制這個產品是否在網站前台公開顯示。',
            websiteVisibilitySlugError: '請先設定 SEO Slug 才能公開顯示',
            websiteVisibilityBlocked: '請先在 Tab 1 建立產品後，才能上傳前台圖片與儲存網站內容。',
            seoSectionTitle: 'SEO 設定',
            seoTitle: 'SEO 標題',
            seoTitlePlaceholder: '輸入搜尋結果顯示的標題',
            seoSlug: 'SEO 網址 (Slug)',
            seoDescription: 'SEO 描述',
            seoDescriptionPlaceholder: '50-160 字左右，提供搜尋結果摘要',
            seoKeywords: 'SEO 關鍵字',
            seoKeywordsPlaceholder: '例如：門禁控制器, SOYAL, 門禁讀卡機',
            summarySectionTitle: '產品摘要',
            summarySectionHint: '這裡會顯示在前台產品標題下方，請一行填一個賣點，前台會自動在每行前面加上符號。',
            summaryPlaceholder: (index: number) => `第 ${index} 行賣點`,
            moveUp: '上移',
            moveDown: '下移',
            addSummaryLine: '新增一行賣點',
            websiteImagesTitle: '產品圖片',
            websiteImagesHint: '拖拉調整順序，第一張為主圖。',
            websiteImageMain: '主圖',
            websiteImageUpload: '上傳圖片',
            websiteImageUploading: '上傳中...',
            websiteImageUploadSuccess: '產品圖片已上傳',
            websiteImageUploadError: '產品圖片上傳失敗',
            websiteImageDeleteConfirm: '確定要刪除這張產品圖片嗎？',
            websiteImageDeleteSuccess: '產品圖片已刪除',
            websiteImageDeleteError: '刪除產品圖片失敗',
            websiteImageSortError: '產品圖片排序儲存失敗',
            websiteImageBlocked: '請先建立產品，再上傳產品圖片。',
            contentImagesTitle: '內容圖文圖片',
            contentImagesHint: '這組圖片會顯示在產品摘要下方、長文介紹上方，適合放橫幅式功能圖、情境圖與說明圖。',
            contentImageUploading: '上傳中...',
            contentImageUpload: '上傳內容圖文圖片',
            contentImageUploadSuccess: '內容圖文圖片已上傳',
            contentImageDeleteSuccess: '內容圖文圖片已刪除',
            contentImageHint: '建議使用 16:9 圖片，適合放橫幅功能圖、情境圖與說明圖。',
            contentImageBlocked: '請先建立產品，再上傳內容圖文圖片。',
            contentImageSortLabel: (index: number) => `排序 #${index}`,
            contentImageOrderLabel: (index: number) => `順序 #${index}`,
            displayContain: '完整顯示',
            displayCover: '滿版裁切',
            contentImageDisplayContainSuccess: '已改為完整顯示',
            contentImageDisplayCoverSuccess: '已改為滿版裁切',
            contentImageDisplayModeUpdateError: '更新內容圖文圖片顯示模式失敗',
            contentIntroTitle: '產品介紹',
            contentIntroHint: '這裡適合放較完整的產品介紹、功能說明、導入方式與其他補充內容。',
            specsTitle: '產品規格',
            videoTitle: '產品影片',
            documentsTitle: '相關文件',
            documentsBlocked: '請先建立產品，再上傳相關文件。',
            faqTitle: '常見問題 FAQ',
            extendedContentTitle: '前台延伸內容設定',
            useCases: '適用場景',
            bestFor: '最適合誰',
            notFor: '不建議情境',
            compatibility: '相容整合 / 協定',
            installationNotes: '安裝提醒',
            maintenanceTips: '維護建議',
            comparisonNotes: '比較建議',
            imageAlt: '圖片 Alt',
            imageCaption: '圖片說明',
            seoReviewTitle: 'SEO 評分與評論（Google Schema）',
            seoReviewHint: '這裡會輸出到前台的 Google 評分與評論結構化資料，請填寫真實可對應的資訊。',
            averageRating: '平均評分（1.0 - 5.0）',
            ratingCount: '評分數量',
            reviewCountWarning: (count: number) => `目前評論筆數有 ${count} 筆，建議評分數量不要小於實際評論筆數。`,
            reviewContent: '評論內容',
            addReview: '新增評論',
            noReviews: '目前尚未新增評論',
            noReviewsHint: '如果要輸出 Google Review Schema，可以在這裡補上代表性評論。',
            reviewIndex: (index: number) => `評論 #${index}`,
            deleteReview: '刪除評論',
            reviewAuthorPlaceholder: '評論者名稱，例如：王先生',
            reviewRating: (rating: number) => `評分 ${rating} 星`,
            reviewBodyPlaceholder: '輸入評論內容，建議填寫真實、可驗證的使用心得。',
            googlePreviewHint: '這是 SEO 標題與描述在搜尋結果中的預覽樣式。',
            productUrlAiTitle: '產品網址與 AI 搜尋',
            productUrl: '產品網址',
            productUrlHint: '可填入原廠或供應商的參考網址，方便後續內容整理與 AI 搜尋輔助。',
            aiSummaryPending: 'AI 摘要功能尚未接上正式流程',
            aiSummaryButton: '產生 AI 摘要',
        },
        seo: {
            saveBlocked: '請先在 Tab 1 建立產品後，再儲存前台內容與 SEO 設定。',
            saveSuccess: 'SEO 設定已儲存',
            saveError: 'SEO 儲存失敗',
            saveButton: '儲存 SEO',
            contentSettingsTitle: 'SEO 內容設定',
            searchSettingsTitle: '搜尋與內容設定',
            targetKeyword: '目標關鍵字',
            searchIntent: '搜尋意圖',
            secondaryKeywords: '次要關鍵字',
            sourceUrl: '來源網址',
            sourceCheckedAt: '來源檢查日期',
            contentStatus: '內容狀態',
            contentReviewedAt: '內容複查日期',
            needsRevalidationTitle: '需要重新驗證內容',
            needsRevalidationHint: '開啟後可提醒這頁後續需要重新檢查資料來源、文案與前台呈現是否仍然正確。',
            checklistTitle: '內容檢查清單',
            checklistComplete: '完成',
            checklistPending: '待補',
        },
        contentImageUploadError: '上傳內容圖文圖片失敗',
        contentImageDeleteConfirm: '確定要刪除這張內容圖文圖片嗎？',
        contentImageDeleteError: '刪除內容圖文圖片失敗',
        contentImageSortError: '更新內容圖文圖片排序失敗',
        removeLine: '刪除',
        generate: '自動產生',
        googlePreview: 'Google 搜尋預覽',
    },
} as const;
