export const adminCaseCopy = {
  nav: {
    dashboard: '儀表板',
    cases: '案件管理',
    customers: '客戶管理',
    products: '產品管理',
    chat: '客服對話',
    pages: '頁面管理',
    settings: '系統設定',
    brand: 'EFAN 管理後台',
    logout: '登出',
  },
  dashboard: {
    title: '案件儀表板',
    subtitle: '快速掌握近況、營收趨勢、待辦項目與最新報價單動態。',
    recentTitle: '最近更新報價單（10筆）',
    viewAll: '查看全部',
    empty: '目前沒有可顯示的報價單。',
    unnamedCase: '(未命名報價單)',
    headers: {
      caseNumber: '報價單號',
      caseName: '報價名稱',
      customer: '客戶',
      updatedAt: '最後更新',
      amount: '金額',
      status: '狀態',
    },
  },
  statCards: {
    revenue: '近30天營收',
    cost: '近30天成本',
    profit: '近30天毛利',
    signed: '近30天成交',
    invoicePending: '待開發票',
    warrantyExpiring: '30天內保固到期',
    construction: '施工中',
    unpaid: '未收款',
    itemSuffix: '筆',
    conversionPrefix: '成交率',
  },
  pendingActions: {
    title: '待處理事項',
    emptyTitle: '目前沒有待處理項目',
    emptyDescription: '案件狀態看起來都很順利，暫時沒有需要你優先追蹤的項目。',
    countSuffix: '筆',
    daySuffix: '天',
    groups: {
      signed: { title: '已簽約待安排', label: '待安排' },
      construction: { title: '施工中待追蹤', label: '施工中' },
      invoice: { title: '待開發票', label: '待開立' },
      unpaid: { title: '未收款', label: '待收款' },
    },
    statuses: {
      signed: '已簽約',
      construction: '施工中',
      completed: '已完工',
    },
  },
  warranty: {
    none: '無保固',
    active: '保固中',
    expired: '已過期',
    remainingDays: (days: number | null) => (days !== null ? `剩餘 ${days} 天` : ''),
  },
} as const;
