export const PRODUCT_PAGE_COPY = {
    breadcrumbHome: '首頁',
    breadcrumbProducts: '產品目錄',
    tabIntro: '產品介紹',
    tabUsage: '使用與維護',
    tabSpecs: '詳細規格',
    tabFaq: '常見問題',
    tabVideo: '產品影片',
    tabDocs: '相關文件',
    selectionGuideEyebrow: 'Selection Guide',
    selectionGuideTitle: '這款產品適不適合你的案場',
    useCasesLabel: '適用場景',
    bestForLabel: '最適合誰',
    notForLabel: '不建議情境',
    comparisonTitle: '比較與補充說明',
    quickSpecsTitle: '快速重點規格',
    compatibilityTitle: '相容與搭配',
    installationTitle: '安裝注意事項',
    maintenanceTitle: '維護建議',
    specGroupFallback: '規格群組',
    relatedEyebrow: 'Related Products',
    relatedTitle: '你也可以一起比較這些型號',
    relatedDescription: '如果你還在評估規格差異、安裝情境或預算配置，可以一起參考同系列或相近定位的產品。',
    compareProductsTitle: '一起比較相近型號',
    compareProductsDescription: '如果你正在評估這款產品，也可以一起比較同系列或相近定位的產品，快速找出更適合的規格與預算配置。',
    compareChecklistTitle: '比較時可以先看這三點',
    compareChecklist: [
        '先確認讀卡方式、通訊介面與核心規格是否符合案場需求。',
        '再看安裝環境、擴充彈性與後續整合需求是否一致。',
        '最後比較預算、交期與維護便利性，選出最合適的型號。',
    ],
    categoryFallback: '產品分類',
    viewProduct: '查看這款',
    videoTitleSuffix: '產品影片',
    imageCoverSuffix: '產品主圖',
    imageGallerySuffix: '產品圖片',
    searchIntentLabels: {
        informational: '資訊查詢',
        transactional: '交易導向',
        commercial: '商業比較',
    },
    searchIntentDescriptions: {
        informational: '這類產品頁以教育與資訊整理為主，適合提供規格、差異與選型參考。',
        transactional: '這類產品頁以明確採購與詢價需求為主，適合強調功能重點、交期與導購資訊。',
        commercial: '這類產品頁以比較、評估與方案規劃為主，適合協助使用者判斷是否符合需求。',
    },
    contentStatusLabels: {
        draft: '草稿',
        reviewed: '已複查',
        published: '已發布',
        stale: '待更新',
    },
    metadataFallbackDescription: '產品介紹、規格整理與選型說明。',
    heroStatementFallback: '的功能特色、規格重點與應用場景整理。',
    docTypes: {
        manual: '說明書',
        dm: 'DM',
        spec: '規格表',
        install: '安裝說明',
        other: '其他',
    },
} as const;
